apiVersion: batch/v1
kind: Job
metadata:
  generateName: django-migrate-
  namespace: ecommerce
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
    argocd.argoproj.io/sync-wave: "5"

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: django-migrate
    spec:
      restartPolicy: OnFailure
      serviceAccountName: django-sa

      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "⏳ Waiting for postgres..."
                sleep 5
              done

        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "⏳ Waiting for redis..."
                sleep 5
              done

        - name: wait-for-secret
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for django-secret readiness..."
              sleep 15

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              echo "🚀 Running Django migrations..."
              python manage.py migrate && \
              echo "🚀 Collecting static files..."
              python manage.py collectstatic --noinput && \
              echo "✅ Migration job completed successfully"

          envFrom:
            - secretRef:
                name: django-secret

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.env.DJANGO_SETTINGS_MODULE }}"

            - name: ALLOWED_HOSTS
              value: "{{ .Values.env.ALLOWED_HOSTS }}"

            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_STORAGE_BUCKET_NAME

            - name: AWS_S3_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_S3_REGION_NAME

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_SECRET_ACCESS_KEY
